### ISSUE TITLE
do not use multi modules projects

### ISSUE THREAD

**Issue by juan-medina** [TheFirstClassCitizen/microservices-2018#21]
I know that the idea behind this repo is to teach others how to do certain staff but multiple module projects, like the one in this repo, are not a good idea. However the could be for other projects

I you have a set of Microservices you may want to do proper CI or even CD on then, and that is not to only build them but as well deploy then independently.

For  example your eureka and zuul may not be change so often as the other projects.

Trigger your CI build and deploy the whole platform because just the dashboard change is not ideal.

However you could bypass this problem by creating a very complicate pipeline that will need to check within the last commit what has change in order to just build, test and deploy the right commponent.

Really not worthy.

Have the project separately, if you like to have something to been able then easily just create a separate project with your bash scripts, or even using submodule/subtree.

**Comment by jabrena** [comment]
This is a good Advice. I will apply in some moment.
